// source: trade.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var enum_pb = require('./enum_pb.js');
goog.object.extend(proto, enum_pb);
var requests_pb = require('./requests_pb.js');
goog.object.extend(proto, requests_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.statistico.Trade', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.Trade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.Trade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.statistico.Trade.displayName = 'proto.statistico.Trade';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.Trade.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.Trade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.Trade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Trade.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    strategyId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    exchange: jspb.Message.getFieldWithDefault(msg, 3, ""),
    exchangeRef: jspb.Message.getFieldWithDefault(msg, 4, ""),
    market: jspb.Message.getFieldWithDefault(msg, 5, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 6, ""),
    exchangePrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    statisticoPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    stake: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    eventId: jspb.Message.getFieldWithDefault(msg, 10, 0),
    competitionId: jspb.Message.getFieldWithDefault(msg, 11, 0),
    seasonId: jspb.Message.getFieldWithDefault(msg, 12, 0),
    eventDate: (f = msg.getEventDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    result: jspb.Message.getFieldWithDefault(msg, 14, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.Trade}
 */
proto.statistico.Trade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.Trade;
  return proto.statistico.Trade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.Trade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.Trade}
 */
proto.statistico.Trade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrategyId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExchange(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExchangeRef(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setExchangePrice(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStatisticoPrice(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStake(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEventId(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCompetitionId(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeasonId(value);
      break;
    case 13:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventDate(value);
      break;
    case 14:
      var value = /** @type {!proto.statistico.TradeResultEnum} */ (reader.readEnum());
      msg.setResult(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.Trade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.Trade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.Trade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Trade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStrategyId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExchange();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExchangeRef();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getExchangePrice();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getStatisticoPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getStake();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getEventId();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getCompetitionId();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
  f = message.getSeasonId();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getEventDate();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      14,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.statistico.Trade.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string strategy_id = 2;
 * @return {string}
 */
proto.statistico.Trade.prototype.getStrategyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setStrategyId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string exchange = 3;
 * @return {string}
 */
proto.statistico.Trade.prototype.getExchange = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setExchange = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string exchange_ref = 4;
 * @return {string}
 */
proto.statistico.Trade.prototype.getExchangeRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setExchangeRef = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string market = 5;
 * @return {string}
 */
proto.statistico.Trade.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setMarket = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string runner = 6;
 * @return {string}
 */
proto.statistico.Trade.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setRunner = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional float exchange_price = 7;
 * @return {number}
 */
proto.statistico.Trade.prototype.getExchangePrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setExchangePrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float statistico_price = 8;
 * @return {number}
 */
proto.statistico.Trade.prototype.getStatisticoPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setStatisticoPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float stake = 9;
 * @return {number}
 */
proto.statistico.Trade.prototype.getStake = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setStake = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional uint64 event_id = 10;
 * @return {number}
 */
proto.statistico.Trade.prototype.getEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setEventId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint64 competition_id = 11;
 * @return {number}
 */
proto.statistico.Trade.prototype.getCompetitionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setCompetitionId = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint64 season_id = 12;
 * @return {number}
 */
proto.statistico.Trade.prototype.getSeasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setSeasonId = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional google.protobuf.Timestamp event_date = 13;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Trade.prototype.getEventDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 13));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.Trade} returns this
*/
proto.statistico.Trade.prototype.setEventDate = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.clearEventDate = function() {
  return this.setEventDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Trade.prototype.hasEventDate = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional TradeResultEnum result = 14;
 * @return {!proto.statistico.TradeResultEnum}
 */
proto.statistico.Trade.prototype.getResult = function() {
  return /** @type {!proto.statistico.TradeResultEnum} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {!proto.statistico.TradeResultEnum} value
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Trade.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.Trade} returns this
*/
proto.statistico.Trade.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Trade.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Trade.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.Trade} returns this
*/
proto.statistico.Trade.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Trade} returns this
 */
proto.statistico.Trade.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Trade.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


goog.object.extend(exports, proto.statistico);
