version: 2.1
orbs:
  artifactory: jfrog/artifactory-orb@1.0.1

workflows:
  version: 2
  build-release-packages:
    jobs:
      - build-release

jobs:
  build-release:
    docker:
      - image: circleci/golang:1.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure
      - run:
          name: Enable Go modules
          command: go version
      - run:
          name: Generate code from proto files
          command: |
            ./bin/generate
      - run:
          name: Release statistico-data Go package
          command: |
            cd ./data/go
            go mod init github.com/statistico/statistico-proto-data
            jfrog rt go-publish v1.0.0 --build-name=statistico-proto-data-go --build-number=${CIRCLE_SHA1}
            jfrog rt build-publish statistico-proto-data-go ${CIRCLE_SHA1}
      - run:
          name: Release statistico-odds-compiler Go package
          command: |
            cd ./odds_compiler/go
            go mod init github.com/statistico/statistico-proto-odds-compiler
            jfrog rt go-publish v1.0.0 --build-name=statistico-proto-odds-compiler-go --build-number=${CIRCLE_SHA1}
            jfrog rt build-publish statistico-proto-odds-compiler-go ${CIRCLE_SHA1}