version: 2.1
workflows:
  version: 2
  build-release-packages:
    jobs:
      - build-release:
          filters:
            tags:
              only: /^v.*/

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:2023.10.1

jobs:
  build-release:
    working_directory: ~/go/src/github.com/statistico/statistico-proto
    executor: machine-executor
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run:
          name: Git tag echo
          command: echo $CIRCLE_TAG
