// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package statistico

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionEnum int32

const (
	ActionEnum_FOR     ActionEnum = 0
	ActionEnum_AGAINST ActionEnum = 1
)

var ActionEnum_name = map[int32]string{
	0: "FOR",
	1: "AGAINST",
}

var ActionEnum_value = map[string]int32{
	"FOR":     0,
	"AGAINST": 1,
}

func (x ActionEnum) String() string {
	return proto.EnumName(ActionEnum_name, int32(x))
}

func (ActionEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

type LineEnum int32

const (
	LineEnum_CLOSING LineEnum = 0
	LineEnum_MAX     LineEnum = 1
)

var LineEnum_name = map[int32]string{
	0: "CLOSING",
	1: "MAX",
}

var LineEnum_value = map[string]int32{
	"CLOSING": 0,
	"MAX":     1,
}

func (x LineEnum) String() string {
	return proto.EnumName(LineEnum_name, int32(x))
}

func (LineEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{1}
}

type MeasureEnum int32

const (
	MeasureEnum_TOTAL      MeasureEnum = 0
	MeasureEnum_AVERAGE    MeasureEnum = 1
	MeasureEnum_CONTINUOUS MeasureEnum = 2
)

var MeasureEnum_name = map[int32]string{
	0: "TOTAL",
	1: "AVERAGE",
	2: "CONTINUOUS",
}

var MeasureEnum_value = map[string]int32{
	"TOTAL":      0,
	"AVERAGE":    1,
	"CONTINUOUS": 2,
}

func (x MeasureEnum) String() string {
	return proto.EnumName(MeasureEnum_name, int32(x))
}

func (MeasureEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{2}
}

type MetricEnum int32

const (
	MetricEnum_GTE MetricEnum = 0
	MetricEnum_LTE MetricEnum = 1
)

var MetricEnum_name = map[int32]string{
	0: "GTE",
	1: "LTE",
}

var MetricEnum_value = map[string]int32{
	"GTE": 0,
	"LTE": 1,
}

func (x MetricEnum) String() string {
	return proto.EnumName(MetricEnum_name, int32(x))
}

func (MetricEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{3}
}

type ResultEnum int32

const (
	ResultEnum_WIN       ResultEnum = 0
	ResultEnum_LOSE      ResultEnum = 1
	ResultEnum_DRAW      ResultEnum = 2
	ResultEnum_WIN_DRAW  ResultEnum = 3
	ResultEnum_LOSE_DRAW ResultEnum = 4
	ResultEnum_WIN_LOSE  ResultEnum = 5
)

var ResultEnum_name = map[int32]string{
	0: "WIN",
	1: "LOSE",
	2: "DRAW",
	3: "WIN_DRAW",
	4: "LOSE_DRAW",
	5: "WIN_LOSE",
}

var ResultEnum_value = map[string]int32{
	"WIN":       0,
	"LOSE":      1,
	"DRAW":      2,
	"WIN_DRAW":  3,
	"LOSE_DRAW": 4,
	"WIN_LOSE":  5,
}

func (x ResultEnum) String() string {
	return proto.EnumName(ResultEnum_name, int32(x))
}

func (ResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{4}
}

type SideEnum int32

const (
	SideEnum_BACK SideEnum = 0
	SideEnum_LAY  SideEnum = 1
)

var SideEnum_name = map[int32]string{
	0: "BACK",
	1: "LAY",
}

var SideEnum_value = map[string]int32{
	"BACK": 0,
	"LAY":  1,
}

func (x SideEnum) String() string {
	return proto.EnumName(SideEnum_name, int32(x))
}

func (SideEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{5}
}

type StakingPlanEnum int32

const (
	StakingPlanEnum_PERCENTAGE StakingPlanEnum = 0
)

var StakingPlanEnum_name = map[int32]string{
	0: "PERCENTAGE",
}

var StakingPlanEnum_value = map[string]int32{
	"PERCENTAGE": 0,
}

func (x StakingPlanEnum) String() string {
	return proto.EnumName(StakingPlanEnum_name, int32(x))
}

func (StakingPlanEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{6}
}

type StatEnum int32

const (
	StatEnum_GOALS         StatEnum = 0
	StatEnum_SHOTS_ON_GOAL StatEnum = 1
)

var StatEnum_name = map[int32]string{
	0: "GOALS",
	1: "SHOTS_ON_GOAL",
}

var StatEnum_value = map[string]int32{
	"GOALS":         0,
	"SHOTS_ON_GOAL": 1,
}

func (x StatEnum) String() string {
	return proto.EnumName(StatEnum_name, int32(x))
}

func (StatEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{7}
}

type StrategyStatusEnum int32

const (
	StrategyStatusEnum_ARCHIVED StrategyStatusEnum = 0
	StrategyStatusEnum_ACTIVE   StrategyStatusEnum = 1
)

var StrategyStatusEnum_name = map[int32]string{
	0: "ARCHIVED",
	1: "ACTIVE",
}

var StrategyStatusEnum_value = map[string]int32{
	"ARCHIVED": 0,
	"ACTIVE":   1,
}

func (x StrategyStatusEnum) String() string {
	return proto.EnumName(StrategyStatusEnum_name, int32(x))
}

func (StrategyStatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{8}
}

type TeamEnum int32

const (
	TeamEnum_HOME_TEAM TeamEnum = 0
	TeamEnum_AWAY_TEAM TeamEnum = 1
)

var TeamEnum_name = map[int32]string{
	0: "HOME_TEAM",
	1: "AWAY_TEAM",
}

var TeamEnum_value = map[string]int32{
	"HOME_TEAM": 0,
	"AWAY_TEAM": 1,
}

func (x TeamEnum) String() string {
	return proto.EnumName(TeamEnum_name, int32(x))
}

func (TeamEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{9}
}

type TradeResultEnum int32

const (
	TradeResultEnum_FAIL    TradeResultEnum = 0
	TradeResultEnum_SUCCESS TradeResultEnum = 1
)

var TradeResultEnum_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
}

var TradeResultEnum_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
}

func (x TradeResultEnum) String() string {
	return proto.EnumName(TradeResultEnum_name, int32(x))
}

func (TradeResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{10}
}

type VenueEnum int32

const (
	VenueEnum_HOME      VenueEnum = 0
	VenueEnum_AWAY      VenueEnum = 1
	VenueEnum_HOME_AWAY VenueEnum = 2
)

var VenueEnum_name = map[int32]string{
	0: "HOME",
	1: "AWAY",
	2: "HOME_AWAY",
}

var VenueEnum_value = map[string]int32{
	"HOME":      0,
	"AWAY":      1,
	"HOME_AWAY": 2,
}

func (x VenueEnum) String() string {
	return proto.EnumName(VenueEnum_name, int32(x))
}

func (VenueEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{11}
}

type VisibilityEnum int32

const (
	VisibilityEnum_PUBLIC  VisibilityEnum = 0
	VisibilityEnum_PRIVATE VisibilityEnum = 1
)

var VisibilityEnum_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}

var VisibilityEnum_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x VisibilityEnum) String() string {
	return proto.EnumName(VisibilityEnum_name, int32(x))
}

func (VisibilityEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{12}
}

func init() {
	proto.RegisterEnum("statistico.ActionEnum", ActionEnum_name, ActionEnum_value)
	proto.RegisterEnum("statistico.LineEnum", LineEnum_name, LineEnum_value)
	proto.RegisterEnum("statistico.MeasureEnum", MeasureEnum_name, MeasureEnum_value)
	proto.RegisterEnum("statistico.MetricEnum", MetricEnum_name, MetricEnum_value)
	proto.RegisterEnum("statistico.ResultEnum", ResultEnum_name, ResultEnum_value)
	proto.RegisterEnum("statistico.SideEnum", SideEnum_name, SideEnum_value)
	proto.RegisterEnum("statistico.StakingPlanEnum", StakingPlanEnum_name, StakingPlanEnum_value)
	proto.RegisterEnum("statistico.StatEnum", StatEnum_name, StatEnum_value)
	proto.RegisterEnum("statistico.StrategyStatusEnum", StrategyStatusEnum_name, StrategyStatusEnum_value)
	proto.RegisterEnum("statistico.TeamEnum", TeamEnum_name, TeamEnum_value)
	proto.RegisterEnum("statistico.TradeResultEnum", TradeResultEnum_name, TradeResultEnum_value)
	proto.RegisterEnum("statistico.VenueEnum", VenueEnum_name, VenueEnum_value)
	proto.RegisterEnum("statistico.VisibilityEnum", VisibilityEnum_name, VisibilityEnum_value)
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor_13a9f1b5947140c8) }

var fileDescriptor_13a9f1b5947140c8 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0x41, 0x6f, 0xda, 0x30,
	0x18, 0x4d, 0x28, 0x05, 0xf3, 0x51, 0xa8, 0xe7, 0xfb, 0xa6, 0x6d, 0xa7, 0xce, 0xd2, 0x98, 0xa6,
	0x6a, 0xa7, 0x9d, 0x4c, 0xea, 0x82, 0xb5, 0x10, 0xa3, 0xd8, 0x84, 0x75, 0x17, 0x14, 0x68, 0xc4,
	0xac, 0x41, 0x98, 0x88, 0x73, 0xe8, 0xbf, 0xaf, 0xec, 0x40, 0xdb, 0x5b, 0xde, 0xe7, 0xf7, 0xde,
	0xe7, 0xf7, 0x62, 0x80, 0xa2, 0xac, 0xf7, 0xa3, 0xff, 0xc7, 0x83, 0x3d, 0x10, 0xa8, 0x6c, 0x6e,
	0x4d, 0x65, 0xcd, 0xe6, 0x40, 0x3f, 0x03, 0xb0, 0x8d, 0x35, 0x87, 0x92, 0x97, 0xf5, 0x9e, 0x74,
	0xe1, 0xe2, 0x5e, 0xa6, 0x38, 0x20, 0x7d, 0xe8, 0xb2, 0x09, 0x13, 0x89, 0xd2, 0x38, 0xa4, 0x1f,
	0x01, 0xc5, 0xa6, 0x2c, 0x3c, 0xa3, 0x0f, 0xdd, 0x28, 0x96, 0x4a, 0x24, 0x13, 0x1c, 0x38, 0xfa,
	0x8c, 0xfd, 0xc6, 0x21, 0xfd, 0x01, 0xfd, 0x59, 0x91, 0x57, 0xf5, 0xb1, 0x21, 0xf5, 0xe0, 0x52,
	0x4b, 0xcd, 0xe2, 0x93, 0x51, 0xc6, 0x53, 0x36, 0xe1, 0x38, 0x24, 0x43, 0x80, 0x48, 0x26, 0x5a,
	0x24, 0x0b, 0xb9, 0x50, 0xb8, 0x45, 0x3f, 0x00, 0xcc, 0x0a, 0x7b, 0x34, 0x9b, 0xf3, 0xf2, 0x89,
	0xe6, 0x8d, 0x6d, 0xac, 0x39, 0x0e, 0xa9, 0x06, 0x48, 0x8b, 0xaa, 0xde, 0xd9, 0xf3, 0xf9, 0x52,
	0x24, 0x38, 0x20, 0x08, 0xda, 0xb1, 0x54, 0xce, 0x10, 0x41, 0xfb, 0x2e, 0x65, 0x4b, 0xdc, 0x22,
	0x57, 0x80, 0x96, 0x22, 0x59, 0x79, 0x74, 0x41, 0x06, 0xd0, 0x73, 0x8c, 0x06, 0xb6, 0xcf, 0x87,
	0x5e, 0x74, 0x49, 0xdf, 0x03, 0x52, 0xe6, 0xb1, 0xb9, 0x29, 0x82, 0xf6, 0x98, 0x45, 0xbf, 0x4e,
	0x4b, 0xd9, 0x03, 0x0e, 0xe9, 0x27, 0xb8, 0x56, 0x36, 0xff, 0x67, 0xca, 0xed, 0x7c, 0x97, 0x37,
	0xb5, 0x0c, 0x01, 0xe6, 0x3c, 0x8d, 0x78, 0xa2, 0x5d, 0x8e, 0x80, 0xde, 0x00, 0x52, 0x36, 0xb7,
	0xe7, 0xac, 0x13, 0xc9, 0x62, 0x85, 0x03, 0xf2, 0x0e, 0x06, 0x6a, 0x2a, 0xb5, 0x5a, 0xc9, 0x64,
	0xe5, 0x66, 0x38, 0xa4, 0x23, 0x20, 0xca, 0x1e, 0x73, 0x5b, 0x6c, 0x9f, 0x9c, 0xa2, 0xae, 0xbc,
	0xe6, 0x0a, 0x10, 0x4b, 0xa3, 0xa9, 0xc8, 0xf8, 0x1d, 0x0e, 0x08, 0x40, 0x87, 0x45, 0x5a, 0x64,
	0x2e, 0xf1, 0x0d, 0x20, 0x5d, 0xe4, 0x7b, 0xcf, 0x1a, 0x40, 0x6f, 0x2a, 0x67, 0x7c, 0xa5, 0x39,
	0x9b, 0xe1, 0xc0, 0x41, 0xb6, 0x64, 0x0f, 0x0d, 0x74, 0xcc, 0x6b, 0x7d, 0xcc, 0x1f, 0x8b, 0x37,
	0x05, 0x21, 0x68, 0xdf, 0x33, 0x71, 0x6a, 0x5d, 0x2d, 0xa2, 0x88, 0x2b, 0xe5, 0xef, 0xd0, 0xcb,
	0x8a, 0xb2, 0x7e, 0x09, 0xec, 0x4c, 0x9b, 0x16, 0x9d, 0x1f, 0x0e, 0x5f, 0x16, 0x79, 0xd8, 0xa2,
	0x5f, 0x60, 0x98, 0x99, 0xca, 0xac, 0xcd, 0xce, 0xd8, 0x27, 0x2f, 0x02, 0xe8, 0xcc, 0x17, 0xe3,
	0x58, 0x44, 0x8d, 0xf5, 0x3c, 0x15, 0x19, 0x73, 0x3f, 0x68, 0x7c, 0xfb, 0xe7, 0xfb, 0xd6, 0xd8,
	0xbf, 0xf5, 0x7a, 0xb4, 0x39, 0xec, 0xbf, 0xbd, 0x3e, 0xab, 0x37, 0x9f, 0x5f, 0xfd, 0x9b, 0xfb,
	0xf9, 0x3a, 0x58, 0x77, 0xfc, 0xe4, 0xf6, 0x39, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xf3, 0xb8, 0xae,
	0x93, 0x02, 0x00, 0x00,
}
