// Code generated by protoc-gen-go. DO NOT EDIT.
// source: performance.proto

package statistico

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamStatPerformanceRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Games                uint32   `protobuf:"varint,2,opt,name=games,proto3" json:"games,omitempty"`
	Measure              string   `protobuf:"bytes,3,opt,name=measure,proto3" json:"measure,omitempty"`
	Metric               string   `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	Seasons              []uint64 `protobuf:"varint,5,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	Stat                 string   `protobuf:"bytes,6,opt,name=stat,proto3" json:"stat,omitempty"`
	Value                float32  `protobuf:"fixed32,7,opt,name=value,proto3" json:"value,omitempty"`
	Venue                string   `protobuf:"bytes,8,opt,name=venue,proto3" json:"venue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStatPerformanceRequest) Reset()         { *m = TeamStatPerformanceRequest{} }
func (m *TeamStatPerformanceRequest) String() string { return proto.CompactTextString(m) }
func (*TeamStatPerformanceRequest) ProtoMessage()    {}
func (*TeamStatPerformanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4cf59bf07e440, []int{0}
}

func (m *TeamStatPerformanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStatPerformanceRequest.Unmarshal(m, b)
}
func (m *TeamStatPerformanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStatPerformanceRequest.Marshal(b, m, deterministic)
}
func (m *TeamStatPerformanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStatPerformanceRequest.Merge(m, src)
}
func (m *TeamStatPerformanceRequest) XXX_Size() int {
	return xxx_messageInfo_TeamStatPerformanceRequest.Size(m)
}
func (m *TeamStatPerformanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStatPerformanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStatPerformanceRequest proto.InternalMessageInfo

func (m *TeamStatPerformanceRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetGames() uint32 {
	if m != nil {
		return m.Games
	}
	return 0
}

func (m *TeamStatPerformanceRequest) GetMeasure() string {
	if m != nil {
		return m.Measure
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetSeasons() []uint64 {
	if m != nil {
		return m.Seasons
	}
	return nil
}

func (m *TeamStatPerformanceRequest) GetStat() string {
	if m != nil {
		return m.Stat
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TeamStatPerformanceRequest) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

type TeamStatResponse struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStatResponse) Reset()         { *m = TeamStatResponse{} }
func (m *TeamStatResponse) String() string { return proto.CompactTextString(m) }
func (*TeamStatResponse) ProtoMessage()    {}
func (*TeamStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4cf59bf07e440, []int{1}
}

func (m *TeamStatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStatResponse.Unmarshal(m, b)
}
func (m *TeamStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStatResponse.Marshal(b, m, deterministic)
}
func (m *TeamStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStatResponse.Merge(m, src)
}
func (m *TeamStatResponse) XXX_Size() int {
	return xxx_messageInfo_TeamStatResponse.Size(m)
}
func (m *TeamStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStatResponse proto.InternalMessageInfo

func (m *TeamStatResponse) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func init() {
	proto.RegisterType((*TeamStatPerformanceRequest)(nil), "statistico.TeamStatPerformanceRequest")
	proto.RegisterType((*TeamStatResponse)(nil), "statistico.TeamStatResponse")
}

func init() { proto.RegisterFile("performance.proto", fileDescriptor_6db4cf59bf07e440) }

var fileDescriptor_6db4cf59bf07e440 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xdf, 0xed, 0xdf, 0xd7, 0x11, 0xa1, 0x86, 0x22, 0xa1, 0x78, 0x58, 0x7a, 0x28, 0x7b,
	0x71, 0xc5, 0xf6, 0xa6, 0x37, 0x2f, 0x9e, 0x04, 0x49, 0x3d, 0x79, 0x10, 0xd2, 0x30, 0xb6, 0x01,
	0xb3, 0xa9, 0x3b, 0xb3, 0xfd, 0xa8, 0x7e, 0x1e, 0x49, 0xe2, 0xb2, 0x45, 0x7a, 0x9b, 0xe7, 0xd9,
	0xdf, 0x3c, 0x3b, 0x33, 0x81, 0xcb, 0x3d, 0xd6, 0x1f, 0xbe, 0x76, 0xba, 0x32, 0x58, 0xee, 0x6b,
	0xcf, 0x5e, 0x00, 0xb1, 0x66, 0x4b, 0x6c, 0x8d, 0x9f, 0x01, 0xa3, 0x76, 0xc9, 0x9f, 0x7f, 0x67,
	0x30, 0x7b, 0x45, 0xed, 0xd6, 0xac, 0xf9, 0xa5, 0xeb, 0x52, 0xf8, 0xd5, 0x20, 0xb1, 0xb8, 0x82,
	0x91, 0x36, 0x6c, 0x7d, 0x25, 0xb3, 0x3c, 0x2b, 0xce, 0xd4, 0xaf, 0x12, 0x53, 0x18, 0x6e, 0xb5,
	0x43, 0x92, 0xbd, 0x3c, 0x2b, 0x2e, 0x54, 0x12, 0x42, 0xc2, 0xd8, 0xa1, 0xa6, 0xa6, 0x46, 0xd9,
	0x8f, 0x78, 0x2b, 0x43, 0x8e, 0x43, 0xae, 0xad, 0x91, 0x83, 0x94, 0x93, 0x54, 0xe8, 0x20, 0xd4,
	0xe4, 0x2b, 0x92, 0xc3, 0xbc, 0x5f, 0x0c, 0x54, 0x2b, 0x85, 0x80, 0x41, 0x18, 0x59, 0x8e, 0x22,
	0x1f, 0xeb, 0xf0, 0xd7, 0x83, 0xfe, 0x6c, 0x50, 0x8e, 0xf3, 0xac, 0xe8, 0xa9, 0x24, 0xa2, 0x8b,
	0x55, 0x83, 0xf2, 0x7f, 0x44, 0x93, 0x98, 0xdf, 0xc3, 0xa4, 0xdd, 0x4b, 0x21, 0xed, 0x7d, 0x45,
	0x28, 0x16, 0x30, 0x0c, 0xab, 0x93, 0xcc, 0xf2, 0x7e, 0x71, 0xbe, 0x9c, 0x94, 0xdd, 0x51, 0xca,
	0x00, 0xab, 0xf4, 0x79, 0xc9, 0x20, 0x8e, 0x6e, 0xb1, 0xc6, 0xfa, 0x60, 0x0d, 0x8a, 0x77, 0x98,
	0x3e, 0x21, 0x07, 0x8e, 0x9e, 0x35, 0x9b, 0x9d, 0xad, 0xb6, 0x21, 0x5d, 0x2c, 0xfe, 0xc6, 0x9c,
	0xbe, 0xe5, 0xec, 0xfa, 0x14, 0xd7, 0xce, 0x36, 0xff, 0xf7, 0xb8, 0x7a, 0xbb, 0xdb, 0x5a, 0xde,
	0x35, 0x9b, 0xd2, 0x78, 0x77, 0xdb, 0xb1, 0x47, 0xe5, 0x4d, 0x7c, 0xb4, 0x87, 0xce, 0xd8, 0x8c,
	0xa2, 0xb3, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x1d, 0x2c, 0x39, 0xf3, 0x01, 0x00, 0x00,
}
