// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: team_stats.proto

package statistico

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamStatsService_GetTeamStatsForFixture_FullMethodName = "/statistico.TeamStatsService/GetTeamStatsForFixture"
)

// TeamStatsServiceClient is the client API for TeamStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamStatsServiceClient interface {
	GetTeamStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*TeamStatsResponse, error)
}

type teamStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamStatsServiceClient(cc grpc.ClientConnInterface) TeamStatsServiceClient {
	return &teamStatsServiceClient{cc}
}

func (c *teamStatsServiceClient) GetTeamStatsForFixture(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*TeamStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeamStatsResponse)
	err := c.cc.Invoke(ctx, TeamStatsService_GetTeamStatsForFixture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamStatsServiceServer is the server API for TeamStatsService service.
// All implementations must embed UnimplementedTeamStatsServiceServer
// for forward compatibility.
type TeamStatsServiceServer interface {
	GetTeamStatsForFixture(context.Context, *FixtureRequest) (*TeamStatsResponse, error)
	mustEmbedUnimplementedTeamStatsServiceServer()
}

// UnimplementedTeamStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamStatsServiceServer struct{}

func (UnimplementedTeamStatsServiceServer) GetTeamStatsForFixture(context.Context, *FixtureRequest) (*TeamStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamStatsForFixture not implemented")
}
func (UnimplementedTeamStatsServiceServer) mustEmbedUnimplementedTeamStatsServiceServer() {}
func (UnimplementedTeamStatsServiceServer) testEmbeddedByValue()                          {}

// UnsafeTeamStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamStatsServiceServer will
// result in compilation errors.
type UnsafeTeamStatsServiceServer interface {
	mustEmbedUnimplementedTeamStatsServiceServer()
}

func RegisterTeamStatsServiceServer(s grpc.ServiceRegistrar, srv TeamStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTeamStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamStatsService_ServiceDesc, srv)
}

func _TeamStatsService_GetTeamStatsForFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamStatsServiceServer).GetTeamStatsForFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamStatsService_GetTeamStatsForFixture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamStatsServiceServer).GetTeamStatsForFixture(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamStatsService_ServiceDesc is the grpc.ServiceDesc for TeamStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistico.TeamStatsService",
	HandlerType: (*TeamStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeamStatsForFixture",
			Handler:    _TeamStatsService_GetTeamStatsForFixture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "team_stats.proto",
}
