// Code generated by protoc-gen-go. DO NOT EDIT.
// source: team.proto

package statistico

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Team struct {
	Id                   uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortCode            *wrappers.StringValue `protobuf:"bytes,3,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	CountryId            uint64                `protobuf:"varint,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	VenueId              uint64                `protobuf:"varint,5,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	IsNationalTeam       *wrappers.BoolValue   `protobuf:"bytes,6,opt,name=is_national_team,json=isNationalTeam,proto3" json:"is_national_team,omitempty"`
	Founded              *wrappers.UInt64Value `protobuf:"bytes,7,opt,name=founded,proto3" json:"founded,omitempty"`
	Logo                 *wrappers.StringValue `protobuf:"bytes,8,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{0}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetShortCode() *wrappers.StringValue {
	if m != nil {
		return m.ShortCode
	}
	return nil
}

func (m *Team) GetCountryId() uint64 {
	if m != nil {
		return m.CountryId
	}
	return 0
}

func (m *Team) GetVenueId() uint64 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *Team) GetIsNationalTeam() *wrappers.BoolValue {
	if m != nil {
		return m.IsNationalTeam
	}
	return nil
}

func (m *Team) GetFounded() *wrappers.UInt64Value {
	if m != nil {
		return m.Founded
	}
	return nil
}

func (m *Team) GetLogo() *wrappers.StringValue {
	if m != nil {
		return m.Logo
	}
	return nil
}

type CompetitionTeamsRequest struct {
	CompetitionId        uint64   `protobuf:"varint,1,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompetitionTeamsRequest) Reset()         { *m = CompetitionTeamsRequest{} }
func (m *CompetitionTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*CompetitionTeamsRequest) ProtoMessage()    {}
func (*CompetitionTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{1}
}

func (m *CompetitionTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompetitionTeamsRequest.Unmarshal(m, b)
}
func (m *CompetitionTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompetitionTeamsRequest.Marshal(b, m, deterministic)
}
func (m *CompetitionTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompetitionTeamsRequest.Merge(m, src)
}
func (m *CompetitionTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_CompetitionTeamsRequest.Size(m)
}
func (m *CompetitionTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompetitionTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompetitionTeamsRequest proto.InternalMessageInfo

func (m *CompetitionTeamsRequest) GetCompetitionId() uint64 {
	if m != nil {
		return m.CompetitionId
	}
	return 0
}

type TeamsResponse struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamsResponse) Reset()         { *m = TeamsResponse{} }
func (m *TeamsResponse) String() string { return proto.CompactTextString(m) }
func (*TeamsResponse) ProtoMessage()    {}
func (*TeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{2}
}

func (m *TeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamsResponse.Unmarshal(m, b)
}
func (m *TeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamsResponse.Marshal(b, m, deterministic)
}
func (m *TeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamsResponse.Merge(m, src)
}
func (m *TeamsResponse) XXX_Size() int {
	return xxx_messageInfo_TeamsResponse.Size(m)
}
func (m *TeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamsResponse proto.InternalMessageInfo

func (m *TeamsResponse) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func init() {
	proto.RegisterType((*Team)(nil), "statistico.Team")
	proto.RegisterType((*CompetitionTeamsRequest)(nil), "statistico.CompetitionTeamsRequest")
	proto.RegisterType((*TeamsResponse)(nil), "statistico.TeamsResponse")
}

func init() { proto.RegisterFile("team.proto", fileDescriptor_8b4e9e93d7b2c6bb) }

var fileDescriptor_8b4e9e93d7b2c6bb = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xd3, 0xb4, 0x69, 0x26, 0x6a, 0x54, 0xed, 0x25, 0xae, 0x05, 0x55, 0x64, 0x04, 0xca,
	0x05, 0xa7, 0xa4, 0xa8, 0x48, 0xf4, 0x82, 0x92, 0x4a, 0xc8, 0x1c, 0x38, 0x38, 0xc0, 0x01, 0x0e,
	0x96, 0xe3, 0x9d, 0xba, 0x2b, 0xd9, 0x3b, 0xc6, 0xbb, 0x2e, 0xca, 0x63, 0xf2, 0x2a, 0x3c, 0x01,
	0xf2, 0xda, 0xad, 0x0d, 0xa1, 0x12, 0xb7, 0xdd, 0x6f, 0xbe, 0x9f, 0xf9, 0x76, 0x01, 0x34, 0x46,
	0x99, 0x97, 0x17, 0xa4, 0x89, 0x81, 0xd2, 0x91, 0x16, 0x4a, 0x8b, 0x98, 0x9c, 0xb3, 0x84, 0x28,
	0x49, 0x71, 0x6e, 0x26, 0x9b, 0xf2, 0x66, 0xfe, 0xa3, 0x88, 0xf2, 0x1c, 0x0b, 0x55, 0x73, 0x9d,
	0x71, 0x81, 0xdf, 0x4b, 0x54, 0xba, 0xb9, 0xbb, 0x3f, 0x7b, 0xd0, 0xff, 0x84, 0x51, 0xc6, 0xc6,
	0xd0, 0x13, 0xdc, 0xb6, 0xa6, 0xd6, 0xac, 0x1f, 0xf4, 0x04, 0x67, 0x0c, 0xfa, 0x32, 0xca, 0xd0,
	0xee, 0x4d, 0xad, 0xd9, 0x30, 0x30, 0x67, 0x76, 0x05, 0xa0, 0x6e, 0xa9, 0xd0, 0x61, 0x4c, 0x1c,
	0xed, 0xfd, 0xa9, 0x35, 0x1b, 0x2d, 0x9e, 0x78, 0x75, 0xa2, 0x77, 0x9f, 0xe8, 0xad, 0x75, 0x21,
	0x64, 0xf2, 0x25, 0x4a, 0x4b, 0x0c, 0x86, 0x86, 0xbf, 0x22, 0x8e, 0xec, 0x29, 0x40, 0x4c, 0xa5,
	0xd4, 0xc5, 0x36, 0x14, 0xdc, 0xee, 0x9b, 0xa0, 0x61, 0x83, 0xf8, 0x9c, 0x9d, 0xc2, 0xd1, 0x1d,
	0xca, 0x12, 0xab, 0xe1, 0x81, 0x19, 0x0e, 0xcc, 0xdd, 0xe7, 0xec, 0x1a, 0x4e, 0x84, 0x0a, 0x65,
	0xa4, 0x05, 0xc9, 0x28, 0x0d, 0xab, 0xe6, 0xf6, 0xa1, 0x09, 0x77, 0x76, 0xc2, 0x97, 0x44, 0x69,
	0x1d, 0x3d, 0x16, 0xea, 0x63, 0x23, 0x31, 0x05, 0x2f, 0x61, 0x70, 0x43, 0xa5, 0xe4, 0xc8, 0xed,
	0xc1, 0x23, 0x9b, 0x7f, 0xf6, 0xa5, 0xbe, 0x7c, 0x5d, 0xcb, 0xef, 0xc9, 0xec, 0x1c, 0xfa, 0x29,
	0x25, 0x64, 0x1f, 0xfd, 0x47, 0x5d, 0xc3, 0x74, 0xdf, 0xc1, 0x64, 0x45, 0x59, 0x8e, 0x5a, 0x54,
	0xf1, 0x55, 0xb8, 0x0a, 0xea, 0x57, 0x67, 0xcf, 0x61, 0x1c, 0xb7, 0xa3, 0xf0, 0xe1, 0xc5, 0x8f,
	0x3b, 0xa8, 0xcf, 0xdd, 0x37, 0x70, 0xdc, 0xc8, 0x54, 0x4e, 0x52, 0x21, 0x7b, 0x01, 0x07, 0x55,
	0x6d, 0x65, 0x5b, 0xd3, 0xfd, 0xd9, 0x68, 0x71, 0xe2, 0xb5, 0x5f, 0xee, 0x55, 0xcc, 0xa0, 0x1e,
	0x2f, 0x7e, 0x59, 0x30, 0xaa, 0xee, 0x6b, 0x2c, 0xee, 0x44, 0x8c, 0xec, 0x2d, 0x8c, 0xde, 0xa3,
	0xae, 0x90, 0xe5, 0xd6, 0xbf, 0x66, 0x93, 0x1d, 0x5d, 0xbd, 0x97, 0xb3, 0x63, 0xe8, 0xee, 0xb1,
	0x6f, 0x30, 0x69, 0xb4, 0x6a, 0xb9, 0x5d, 0x75, 0xf7, 0x63, 0xcf, 0xba, 0xf4, 0x47, 0xba, 0x3a,
	0xa7, 0x7f, 0x7b, 0x3e, 0xd4, 0x71, 0xf7, 0xd8, 0x07, 0x60, 0xad, 0xf9, 0x1a, 0x23, 0x65, 0x7c,
	0xcf, 0xba, 0x92, 0x1a, 0xfd, 0xc3, 0xf2, 0x1f, 0x6b, 0x9e, 0x5b, 0xcb, 0x8b, 0xaf, 0xaf, 0x12,
	0xa1, 0x6f, 0xcb, 0x8d, 0x17, 0x53, 0x36, 0x6f, 0x19, 0x9d, 0xe3, 0x4b, 0xf3, 0x5d, 0x57, 0x2d,
	0xb0, 0x39, 0x34, 0xc8, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xb8, 0x4f, 0xd4, 0x49,
	0x03, 0x00, 0x00,
}
