# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fixture.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import competition_pb2 as competition__pb2
import requests_pb2 as requests__pb2
import round_pb2 as round__pb2
import season_pb2 as season__pb2
import team_pb2 as team__pb2
import venue_pb2 as venue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfixture.proto\x12\nstatistico\x1a\x0c\x63ommon.proto\x1a\x11\x63ompetition.proto\x1a\x0erequests.proto\x1a\x0bround.proto\x1a\x0cseason.proto\x1a\nteam.proto\x1a\x0bvenue.proto\"\x9a\x02\n\x07\x46ixture\x12\n\n\x02id\x18\x01 \x01(\x03\x12,\n\x0b\x63ompetition\x18\x02 \x01(\x0b\x32\x17.statistico.Competition\x12\"\n\x06season\x18\x03 \x01(\x0b\x32\x12.statistico.Season\x12#\n\thome_team\x18\x04 \x01(\x0b\x32\x10.statistico.Team\x12#\n\taway_team\x18\x05 \x01(\x0b\x32\x10.statistico.Team\x12 \n\x05round\x18\x06 \x01(\x0b\x32\x11.statistico.Round\x12 \n\x05venue\x18\x07 \x01(\x0b\x32\x11.statistico.Venue\x12#\n\tdate_time\x18\x08 \x01(\x0b\x32\x10.statistico.Date2\xe8\x01\n\x0e\x46ixtureService\x12O\n\x12ListSeasonFixtures\x12 .statistico.SeasonFixtureRequest\x1a\x13.statistico.Fixture\"\x00\x30\x01\x12@\n\x0b\x46ixtureByID\x12\x1a.statistico.FixtureRequest\x1a\x13.statistico.Fixture\"\x00\x12\x43\n\x06Search\x12 .statistico.FixtureSearchRequest\x1a\x13.statistico.Fixture\"\x00\x30\x01\x42\x33Z1github.com/statistico/statistico-proto;statisticob\x06proto3')



_FIXTURE = DESCRIPTOR.message_types_by_name['Fixture']
Fixture = _reflection.GeneratedProtocolMessageType('Fixture', (_message.Message,), {
  'DESCRIPTOR' : _FIXTURE,
  '__module__' : 'fixture_pb2'
  # @@protoc_insertion_point(class_scope:statistico.Fixture)
  })
_sym_db.RegisterMessage(Fixture)

_FIXTURESERVICE = DESCRIPTOR.services_by_name['FixtureService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/statistico/statistico-proto;statistico'
  _FIXTURE._serialized_start=131
  _FIXTURE._serialized_end=413
  _FIXTURESERVICE._serialized_start=416
  _FIXTURESERVICE._serialized_end=648
# @@protoc_insertion_point(module_scope)
