# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import requests_pb2 as requests__pb2
import season_pb2 as season__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in season_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeasonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeasonsForCompetition = channel.unary_stream(
                '/statistico.SeasonService/GetSeasonsForCompetition',
                request_serializer=requests__pb2.SeasonCompetitionRequest.SerializeToString,
                response_deserializer=season__pb2.Season.FromString,
                _registered_method=True)
        self.GetSeasonsForTeam = channel.unary_unary(
                '/statistico.SeasonService/GetSeasonsForTeam',
                request_serializer=season__pb2.TeamSeasonsRequest.SerializeToString,
                response_deserializer=season__pb2.TeamSeasonsResponse.FromString,
                _registered_method=True)


class SeasonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSeasonsForCompetition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeasonsForTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeasonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeasonsForCompetition': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSeasonsForCompetition,
                    request_deserializer=requests__pb2.SeasonCompetitionRequest.FromString,
                    response_serializer=season__pb2.Season.SerializeToString,
            ),
            'GetSeasonsForTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeasonsForTeam,
                    request_deserializer=season__pb2.TeamSeasonsRequest.FromString,
                    response_serializer=season__pb2.TeamSeasonsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistico.SeasonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statistico.SeasonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeasonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeasonsForCompetition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/statistico.SeasonService/GetSeasonsForCompetition',
            requests__pb2.SeasonCompetitionRequest.SerializeToString,
            season__pb2.Season.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeasonsForTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistico.SeasonService/GetSeasonsForTeam',
            season__pb2.TeamSeasonsRequest.SerializeToString,
            season__pb2.TeamSeasonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
