# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import requests_pb2 as requests__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_stats.proto',
  package='statistico_proto_data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12player_stats.proto\x12\x15statistico_proto_data\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0erequests.proto\"\x83\x01\n\x13PlayerStatsResponse\x12\x35\n\thome_team\x18\x01 \x03(\x0b\x32\".statistico_proto_data.PlayerStats\x12\x35\n\taway_team\x18\x02 \x03(\x0b\x32\".statistico_proto_data.PlayerStats\"t\n\x0eLineupResponse\x12\x30\n\thome_team\x18\x01 \x01(\x0b\x32\x1d.statistico_proto_data.Lineup\x12\x30\n\taway_team\x18\x02 \x01(\x0b\x32\x1d.statistico_proto_data.Lineup\"\x9c\x02\n\x0bPlayerStats\x12\x11\n\tplayer_id\x18\x01 \x01(\x04\x12\x30\n\x0bshots_total\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x32\n\rshots_on_goal\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x31\n\x0cgoals_scored\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x33\n\x0egoals_conceded\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12,\n\x07\x61ssists\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"p\n\x06Lineup\x12\x32\n\x05start\x18\x01 \x03(\x0b\x32#.statistico_proto_data.LineupPlayer\x12\x32\n\x05\x62\x65nch\x18\x02 \x03(\x0b\x32#.statistico_proto_data.LineupPlayer\"\x84\x01\n\x0cLineupPlayer\x12\x11\n\tplayer_id\x18\x01 \x01(\x04\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x38\n\x12\x66ormation_position\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x15\n\ris_substitute\x18\x04 \x01(\x08\x32\xec\x01\n\x12PlayerStatsService\x12o\n\x18GetPlayerStatsForFixture\x12%.statistico_proto_data.FixtureRequest\x1a*.statistico_proto_data.PlayerStatsResponse\"\x00\x12\x65\n\x13GetLineUpForFixture\x12%.statistico_proto_data.FixtureRequest\x1a%.statistico_proto_data.LineupResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,requests__pb2.DESCRIPTOR,])




_PLAYERSTATSRESPONSE = _descriptor.Descriptor(
  name='PlayerStatsResponse',
  full_name='statistico_proto_data.PlayerStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='home_team', full_name='statistico_proto_data.PlayerStatsResponse.home_team', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='away_team', full_name='statistico_proto_data.PlayerStatsResponse.away_team', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=225,
)


_LINEUPRESPONSE = _descriptor.Descriptor(
  name='LineupResponse',
  full_name='statistico_proto_data.LineupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='home_team', full_name='statistico_proto_data.LineupResponse.home_team', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='away_team', full_name='statistico_proto_data.LineupResponse.away_team', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=343,
)


_PLAYERSTATS = _descriptor.Descriptor(
  name='PlayerStats',
  full_name='statistico_proto_data.PlayerStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='statistico_proto_data.PlayerStats.player_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shots_total', full_name='statistico_proto_data.PlayerStats.shots_total', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shots_on_goal', full_name='statistico_proto_data.PlayerStats.shots_on_goal', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goals_scored', full_name='statistico_proto_data.PlayerStats.goals_scored', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goals_conceded', full_name='statistico_proto_data.PlayerStats.goals_conceded', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assists', full_name='statistico_proto_data.PlayerStats.assists', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=630,
)


_LINEUP = _descriptor.Descriptor(
  name='Lineup',
  full_name='statistico_proto_data.Lineup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='statistico_proto_data.Lineup.start', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bench', full_name='statistico_proto_data.Lineup.bench', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=744,
)


_LINEUPPLAYER = _descriptor.Descriptor(
  name='LineupPlayer',
  full_name='statistico_proto_data.LineupPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='statistico_proto_data.LineupPlayer.player_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='statistico_proto_data.LineupPlayer.position', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='formation_position', full_name='statistico_proto_data.LineupPlayer.formation_position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_substitute', full_name='statistico_proto_data.LineupPlayer.is_substitute', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=747,
  serialized_end=879,
)

_PLAYERSTATSRESPONSE.fields_by_name['home_team'].message_type = _PLAYERSTATS
_PLAYERSTATSRESPONSE.fields_by_name['away_team'].message_type = _PLAYERSTATS
_LINEUPRESPONSE.fields_by_name['home_team'].message_type = _LINEUP
_LINEUPRESPONSE.fields_by_name['away_team'].message_type = _LINEUP
_PLAYERSTATS.fields_by_name['shots_total'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_PLAYERSTATS.fields_by_name['shots_on_goal'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_PLAYERSTATS.fields_by_name['goals_scored'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_PLAYERSTATS.fields_by_name['goals_conceded'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_PLAYERSTATS.fields_by_name['assists'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_LINEUP.fields_by_name['start'].message_type = _LINEUPPLAYER
_LINEUP.fields_by_name['bench'].message_type = _LINEUPPLAYER
_LINEUPPLAYER.fields_by_name['formation_position'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['PlayerStatsResponse'] = _PLAYERSTATSRESPONSE
DESCRIPTOR.message_types_by_name['LineupResponse'] = _LINEUPRESPONSE
DESCRIPTOR.message_types_by_name['PlayerStats'] = _PLAYERSTATS
DESCRIPTOR.message_types_by_name['Lineup'] = _LINEUP
DESCRIPTOR.message_types_by_name['LineupPlayer'] = _LINEUPPLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerStatsResponse = _reflection.GeneratedProtocolMessageType('PlayerStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSTATSRESPONSE,
  '__module__' : 'player_stats_pb2'
  # @@protoc_insertion_point(class_scope:statistico_proto_data.PlayerStatsResponse)
  })
_sym_db.RegisterMessage(PlayerStatsResponse)

LineupResponse = _reflection.GeneratedProtocolMessageType('LineupResponse', (_message.Message,), {
  'DESCRIPTOR' : _LINEUPRESPONSE,
  '__module__' : 'player_stats_pb2'
  # @@protoc_insertion_point(class_scope:statistico_proto_data.LineupResponse)
  })
_sym_db.RegisterMessage(LineupResponse)

PlayerStats = _reflection.GeneratedProtocolMessageType('PlayerStats', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSTATS,
  '__module__' : 'player_stats_pb2'
  # @@protoc_insertion_point(class_scope:statistico_proto_data.PlayerStats)
  })
_sym_db.RegisterMessage(PlayerStats)

Lineup = _reflection.GeneratedProtocolMessageType('Lineup', (_message.Message,), {
  'DESCRIPTOR' : _LINEUP,
  '__module__' : 'player_stats_pb2'
  # @@protoc_insertion_point(class_scope:statistico_proto_data.Lineup)
  })
_sym_db.RegisterMessage(Lineup)

LineupPlayer = _reflection.GeneratedProtocolMessageType('LineupPlayer', (_message.Message,), {
  'DESCRIPTOR' : _LINEUPPLAYER,
  '__module__' : 'player_stats_pb2'
  # @@protoc_insertion_point(class_scope:statistico_proto_data.LineupPlayer)
  })
_sym_db.RegisterMessage(LineupPlayer)



_PLAYERSTATSSERVICE = _descriptor.ServiceDescriptor(
  name='PlayerStatsService',
  full_name='statistico_proto_data.PlayerStatsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=882,
  serialized_end=1118,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlayerStatsForFixture',
    full_name='statistico_proto_data.PlayerStatsService.GetPlayerStatsForFixture',
    index=0,
    containing_service=None,
    input_type=requests__pb2._FIXTUREREQUEST,
    output_type=_PLAYERSTATSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLineUpForFixture',
    full_name='statistico_proto_data.PlayerStatsService.GetLineUpForFixture',
    index=1,
    containing_service=None,
    input_type=requests__pb2._FIXTUREREQUEST,
    output_type=_LINEUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYERSTATSSERVICE)

DESCRIPTOR.services_by_name['PlayerStatsService'] = _PLAYERSTATSSERVICE

# @@protoc_insertion_point(module_scope)
