// Code generated by protoc-gen-go. DO NOT EDIT.
// source: performance.proto

package statisticodata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamStatPerformanceRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Games                uint32   `protobuf:"varint,2,opt,name=games,proto3" json:"games,omitempty"`
	Measure              string   `protobuf:"bytes,3,opt,name=measure,proto3" json:"measure,omitempty"`
	Metric               string   `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	Seasons              []uint64 `protobuf:"varint,5,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	Stat                 string   `protobuf:"bytes,6,opt,name=stat,proto3" json:"stat,omitempty"`
	Value                float32  `protobuf:"fixed32,7,opt,name=value,proto3" json:"value,omitempty"`
	Venue                string   `protobuf:"bytes,8,opt,name=venue,proto3" json:"venue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStatPerformanceRequest) Reset()         { *m = TeamStatPerformanceRequest{} }
func (m *TeamStatPerformanceRequest) String() string { return proto.CompactTextString(m) }
func (*TeamStatPerformanceRequest) ProtoMessage()    {}
func (*TeamStatPerformanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4cf59bf07e440, []int{0}
}

func (m *TeamStatPerformanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStatPerformanceRequest.Unmarshal(m, b)
}
func (m *TeamStatPerformanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStatPerformanceRequest.Marshal(b, m, deterministic)
}
func (m *TeamStatPerformanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStatPerformanceRequest.Merge(m, src)
}
func (m *TeamStatPerformanceRequest) XXX_Size() int {
	return xxx_messageInfo_TeamStatPerformanceRequest.Size(m)
}
func (m *TeamStatPerformanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStatPerformanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStatPerformanceRequest proto.InternalMessageInfo

func (m *TeamStatPerformanceRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetGames() uint32 {
	if m != nil {
		return m.Games
	}
	return 0
}

func (m *TeamStatPerformanceRequest) GetMeasure() string {
	if m != nil {
		return m.Measure
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetSeasons() []uint64 {
	if m != nil {
		return m.Seasons
	}
	return nil
}

func (m *TeamStatPerformanceRequest) GetStat() string {
	if m != nil {
		return m.Stat
	}
	return ""
}

func (m *TeamStatPerformanceRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TeamStatPerformanceRequest) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

type TeamStatResponse struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStatResponse) Reset()         { *m = TeamStatResponse{} }
func (m *TeamStatResponse) String() string { return proto.CompactTextString(m) }
func (*TeamStatResponse) ProtoMessage()    {}
func (*TeamStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db4cf59bf07e440, []int{1}
}

func (m *TeamStatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStatResponse.Unmarshal(m, b)
}
func (m *TeamStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStatResponse.Marshal(b, m, deterministic)
}
func (m *TeamStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStatResponse.Merge(m, src)
}
func (m *TeamStatResponse) XXX_Size() int {
	return xxx_messageInfo_TeamStatResponse.Size(m)
}
func (m *TeamStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStatResponse proto.InternalMessageInfo

func (m *TeamStatResponse) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func init() {
	proto.RegisterType((*TeamStatPerformanceRequest)(nil), "statisticodata.TeamStatPerformanceRequest")
	proto.RegisterType((*TeamStatResponse)(nil), "statisticodata.TeamStatResponse")
}

func init() {
	proto.RegisterFile("performance.proto", fileDescriptor_6db4cf59bf07e440)
}

var fileDescriptor_6db4cf59bf07e440 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbd, 0x4e, 0x43, 0x21,
	0x14, 0x80, 0xbd, 0xfd, 0x55, 0x8c, 0x46, 0x49, 0x63, 0x48, 0x27, 0xd2, 0xe9, 0xa6, 0x43, 0x87,
	0xba, 0xbb, 0x3a, 0x99, 0x18, 0xea, 0x0b, 0x1c, 0xf1, 0xb4, 0x92, 0x08, 0x54, 0xce, 0xb9, 0x9d,
	0x7c, 0x4e, 0x9f, 0xc7, 0x00, 0xde, 0xa8, 0x49, 0xdd, 0xf8, 0xe0, 0x3b, 0xbf, 0x88, 0xeb, 0x3d,
	0xa6, 0x6d, 0x4c, 0x1e, 0x82, 0xc5, 0xd5, 0x3e, 0x45, 0x8e, 0xf2, 0x92, 0x18, 0xd8, 0x11, 0x3b,
	0x1b, 0x5f, 0x80, 0x61, 0x2e, 0x18, 0xc1, 0xd7, 0xb7, 0xc5, 0x67, 0x23, 0xe6, 0x4f, 0x08, 0x7e,
	0xc3, 0xc0, 0x8f, 0x3f, 0x91, 0x06, 0xdf, 0x3b, 0x24, 0x96, 0x37, 0x62, 0x02, 0x96, 0x5d, 0x0c,
	0xaa, 0xd1, 0x4d, 0x7b, 0x66, 0xbe, 0x49, 0xce, 0xc4, 0x78, 0x07, 0x1e, 0x49, 0x0d, 0x74, 0xd3,
	0x5e, 0x98, 0x0a, 0x52, 0x89, 0xa9, 0x47, 0xa0, 0x2e, 0xa1, 0x1a, 0x16, 0xbd, 0xc7, 0x9c, 0xc7,
	0x23, 0x27, 0x67, 0xd5, 0xa8, 0xe6, 0xa9, 0x94, 0x23, 0x08, 0x81, 0x62, 0x20, 0x35, 0xd6, 0xc3,
	0x76, 0x64, 0x7a, 0x94, 0x52, 0x8c, 0x72, 0xdb, 0x6a, 0x52, 0xfc, 0x72, 0xce, 0x55, 0x0f, 0xf0,
	0xd6, 0xa1, 0x9a, 0xea, 0xa6, 0x1d, 0x98, 0x0a, 0xe5, 0x16, 0x43, 0x87, 0xea, 0xb4, 0xa8, 0x15,
	0x16, 0x77, 0xe2, 0xaa, 0x9f, 0xcb, 0x20, 0xed, 0x63, 0x20, 0x94, 0x4b, 0x31, 0xce, 0xa3, 0x93,
	0x6a, 0xf4, 0xb0, 0x3d, 0x5f, 0xcf, 0x56, 0x7f, 0x17, 0xb3, 0xca, 0x01, 0xa6, 0x2a, 0xeb, 0x0f,
	0x21, 0x7f, 0xed, 0x63, 0x83, 0xe9, 0xe0, 0x2c, 0xca, 0xad, 0x98, 0xdd, 0x23, 0x67, 0x8f, 0x1e,
	0x80, 0xed, 0xab, 0x0b, 0xbb, 0x5c, 0x41, 0x2e, 0x8f, 0xa5, 0x3a, 0xbe, 0xd3, 0xb9, 0xfe, 0xcf,
	0xed, 0xfb, 0x5c, 0x9c, 0x3c, 0x4f, 0xca, 0xef, 0xdc, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0xb9, 0xa8, 0x83, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PerformanceServiceClient is the client API for PerformanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PerformanceServiceClient interface {
	GetTeamsMatchingStat(ctx context.Context, in *TeamStatPerformanceRequest, opts ...grpc.CallOption) (*TeamStatResponse, error)
}

type performanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformanceServiceClient(cc grpc.ClientConnInterface) PerformanceServiceClient {
	return &performanceServiceClient{cc}
}

func (c *performanceServiceClient) GetTeamsMatchingStat(ctx context.Context, in *TeamStatPerformanceRequest, opts ...grpc.CallOption) (*TeamStatResponse, error) {
	out := new(TeamStatResponse)
	err := c.cc.Invoke(ctx, "/statisticodata.PerformanceService/GetTeamsMatchingStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerformanceServiceServer is the server API for PerformanceService service.
type PerformanceServiceServer interface {
	GetTeamsMatchingStat(context.Context, *TeamStatPerformanceRequest) (*TeamStatResponse, error)
}

// UnimplementedPerformanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPerformanceServiceServer struct {
}

func (*UnimplementedPerformanceServiceServer) GetTeamsMatchingStat(ctx context.Context, req *TeamStatPerformanceRequest) (*TeamStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsMatchingStat not implemented")
}

func RegisterPerformanceServiceServer(s *grpc.Server, srv PerformanceServiceServer) {
	s.RegisterService(&_PerformanceService_serviceDesc, srv)
}

func _PerformanceService_GetTeamsMatchingStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamStatPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetTeamsMatchingStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statisticodata.PerformanceService/GetTeamsMatchingStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetTeamsMatchingStat(ctx, req.(*TeamStatPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PerformanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "statisticodata.PerformanceService",
	HandlerType: (*PerformanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeamsMatchingStat",
			Handler:    _PerformanceService_GetTeamsMatchingStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "performance.proto",
}
