// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requests.proto

package statisticodata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompetitionRequest struct {
	// A filter to limit the competitions returned associated to a specific countries
	CountryIds []uint64 `protobuf:"varint,1,rep,packed,name=country_ids,json=countryIds,proto3" json:"country_ids,omitempty"`
	// Order the ID column to return competitions in specific order
	Sort *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// A filter to limit the competitions returned depending on if they are a cup competition or not
	IsCup                *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_cup,json=isCup,proto3" json:"is_cup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CompetitionRequest) Reset()         { *m = CompetitionRequest{} }
func (m *CompetitionRequest) String() string { return proto.CompactTextString(m) }
func (*CompetitionRequest) ProtoMessage()    {}
func (*CompetitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{0}
}

func (m *CompetitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompetitionRequest.Unmarshal(m, b)
}
func (m *CompetitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompetitionRequest.Marshal(b, m, deterministic)
}
func (m *CompetitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompetitionRequest.Merge(m, src)
}
func (m *CompetitionRequest) XXX_Size() int {
	return xxx_messageInfo_CompetitionRequest.Size(m)
}
func (m *CompetitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompetitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompetitionRequest proto.InternalMessageInfo

func (m *CompetitionRequest) GetCountryIds() []uint64 {
	if m != nil {
		return m.CountryIds
	}
	return nil
}

func (m *CompetitionRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *CompetitionRequest) GetIsCup() *wrappers.BoolValue {
	if m != nil {
		return m.IsCup
	}
	return nil
}

type FixtureRequest struct {
	FixtureId            uint64   `protobuf:"varint,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixtureRequest) Reset()         { *m = FixtureRequest{} }
func (m *FixtureRequest) String() string { return proto.CompactTextString(m) }
func (*FixtureRequest) ProtoMessage()    {}
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{1}
}

func (m *FixtureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureRequest.Unmarshal(m, b)
}
func (m *FixtureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureRequest.Marshal(b, m, deterministic)
}
func (m *FixtureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureRequest.Merge(m, src)
}
func (m *FixtureRequest) XXX_Size() int {
	return xxx_messageInfo_FixtureRequest.Size(m)
}
func (m *FixtureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureRequest proto.InternalMessageInfo

func (m *FixtureRequest) GetFixtureId() uint64 {
	if m != nil {
		return m.FixtureId
	}
	return 0
}

type FixtureSearchRequest struct {
	// A filter to limit the results returned associated to a specific season
	SeasonIds []uint64 `protobuf:"varint,1,rep,packed,name=season_ids,json=seasonIds,proto3" json:"season_ids,omitempty"`
	// The number of results to return.
	Limit *wrappers.UInt64Value `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// A filter to return Results before a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateBefore *wrappers.StringValue `protobuf:"bytes,3,opt,name=date_before,json=dateBefore,proto3" json:"date_before,omitempty"`
	// A filter to return Results after a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateAfter *wrappers.StringValue `protobuf:"bytes,4,opt,name=date_after,json=dateAfter,proto3" json:"date_after,omitempty"`
	// Order the date column to return results in specific order
	Sort                 *wrappers.StringValue `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FixtureSearchRequest) Reset()         { *m = FixtureSearchRequest{} }
func (m *FixtureSearchRequest) String() string { return proto.CompactTextString(m) }
func (*FixtureSearchRequest) ProtoMessage()    {}
func (*FixtureSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{2}
}

func (m *FixtureSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixtureSearchRequest.Unmarshal(m, b)
}
func (m *FixtureSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixtureSearchRequest.Marshal(b, m, deterministic)
}
func (m *FixtureSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixtureSearchRequest.Merge(m, src)
}
func (m *FixtureSearchRequest) XXX_Size() int {
	return xxx_messageInfo_FixtureSearchRequest.Size(m)
}
func (m *FixtureSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FixtureSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FixtureSearchRequest proto.InternalMessageInfo

func (m *FixtureSearchRequest) GetSeasonIds() []uint64 {
	if m != nil {
		return m.SeasonIds
	}
	return nil
}

func (m *FixtureSearchRequest) GetLimit() *wrappers.UInt64Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *FixtureSearchRequest) GetDateBefore() *wrappers.StringValue {
	if m != nil {
		return m.DateBefore
	}
	return nil
}

func (m *FixtureSearchRequest) GetDateAfter() *wrappers.StringValue {
	if m != nil {
		return m.DateAfter
	}
	return nil
}

func (m *FixtureSearchRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

type HistoricalResultRequest struct {
	// The Home Team ID that the Result set relates to
	HomeTeamId uint64 `protobuf:"varint,1,opt,name=home_team_id,json=homeTeamId,proto3" json:"home_team_id,omitempty"`
	// The Away Team ID that the Result set relates to
	AwayTeamId uint64 `protobuf:"varint,2,opt,name=away_team_id,json=awayTeamId,proto3" json:"away_team_id,omitempty"`
	// The number of results to return
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// A filter to return Results before a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateBefore           string   `protobuf:"bytes,4,opt,name=date_before,json=dateBefore,proto3" json:"date_before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoricalResultRequest) Reset()         { *m = HistoricalResultRequest{} }
func (m *HistoricalResultRequest) String() string { return proto.CompactTextString(m) }
func (*HistoricalResultRequest) ProtoMessage()    {}
func (*HistoricalResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{3}
}

func (m *HistoricalResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoricalResultRequest.Unmarshal(m, b)
}
func (m *HistoricalResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoricalResultRequest.Marshal(b, m, deterministic)
}
func (m *HistoricalResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalResultRequest.Merge(m, src)
}
func (m *HistoricalResultRequest) XXX_Size() int {
	return xxx_messageInfo_HistoricalResultRequest.Size(m)
}
func (m *HistoricalResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalResultRequest proto.InternalMessageInfo

func (m *HistoricalResultRequest) GetHomeTeamId() uint64 {
	if m != nil {
		return m.HomeTeamId
	}
	return 0
}

func (m *HistoricalResultRequest) GetAwayTeamId() uint64 {
	if m != nil {
		return m.AwayTeamId
	}
	return 0
}

func (m *HistoricalResultRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *HistoricalResultRequest) GetDateBefore() string {
	if m != nil {
		return m.DateBefore
	}
	return ""
}

type ResultRequest struct {
	FixtureId            uint64   `protobuf:"varint,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultRequest) Reset()         { *m = ResultRequest{} }
func (m *ResultRequest) String() string { return proto.CompactTextString(m) }
func (*ResultRequest) ProtoMessage()    {}
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{4}
}

func (m *ResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRequest.Unmarshal(m, b)
}
func (m *ResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRequest.Marshal(b, m, deterministic)
}
func (m *ResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRequest.Merge(m, src)
}
func (m *ResultRequest) XXX_Size() int {
	return xxx_messageInfo_ResultRequest.Size(m)
}
func (m *ResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRequest proto.InternalMessageInfo

func (m *ResultRequest) GetFixtureId() uint64 {
	if m != nil {
		return m.FixtureId
	}
	return 0
}

type SeasonCompetitionRequest struct {
	CompetitionId uint64 `protobuf:"varint,1,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty"`
	// Order the name column to return seasons in specific order
	Sort                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SeasonCompetitionRequest) Reset()         { *m = SeasonCompetitionRequest{} }
func (m *SeasonCompetitionRequest) String() string { return proto.CompactTextString(m) }
func (*SeasonCompetitionRequest) ProtoMessage()    {}
func (*SeasonCompetitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{5}
}

func (m *SeasonCompetitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasonCompetitionRequest.Unmarshal(m, b)
}
func (m *SeasonCompetitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasonCompetitionRequest.Marshal(b, m, deterministic)
}
func (m *SeasonCompetitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasonCompetitionRequest.Merge(m, src)
}
func (m *SeasonCompetitionRequest) XXX_Size() int {
	return xxx_messageInfo_SeasonCompetitionRequest.Size(m)
}
func (m *SeasonCompetitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasonCompetitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeasonCompetitionRequest proto.InternalMessageInfo

func (m *SeasonCompetitionRequest) GetCompetitionId() uint64 {
	if m != nil {
		return m.CompetitionId
	}
	return 0
}

func (m *SeasonCompetitionRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

type SeasonRequest struct {
	// The Season ID that the Result set relates to
	SeasonId int64 `protobuf:"varint,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	// A filter to return Results before a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateBefore           string   `protobuf:"bytes,2,opt,name=date_before,json=dateBefore,proto3" json:"date_before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeasonRequest) Reset()         { *m = SeasonRequest{} }
func (m *SeasonRequest) String() string { return proto.CompactTextString(m) }
func (*SeasonRequest) ProtoMessage()    {}
func (*SeasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{6}
}

func (m *SeasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasonRequest.Unmarshal(m, b)
}
func (m *SeasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasonRequest.Marshal(b, m, deterministic)
}
func (m *SeasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasonRequest.Merge(m, src)
}
func (m *SeasonRequest) XXX_Size() int {
	return xxx_messageInfo_SeasonRequest.Size(m)
}
func (m *SeasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeasonRequest proto.InternalMessageInfo

func (m *SeasonRequest) GetSeasonId() int64 {
	if m != nil {
		return m.SeasonId
	}
	return 0
}

func (m *SeasonRequest) GetDateBefore() string {
	if m != nil {
		return m.DateBefore
	}
	return ""
}

type SeasonTeamsRequest struct {
	SeasonId             uint64   `protobuf:"varint,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeasonTeamsRequest) Reset()         { *m = SeasonTeamsRequest{} }
func (m *SeasonTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*SeasonTeamsRequest) ProtoMessage()    {}
func (*SeasonTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{7}
}

func (m *SeasonTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasonTeamsRequest.Unmarshal(m, b)
}
func (m *SeasonTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasonTeamsRequest.Marshal(b, m, deterministic)
}
func (m *SeasonTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasonTeamsRequest.Merge(m, src)
}
func (m *SeasonTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_SeasonTeamsRequest.Size(m)
}
func (m *SeasonTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasonTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeasonTeamsRequest proto.InternalMessageInfo

func (m *SeasonTeamsRequest) GetSeasonId() uint64 {
	if m != nil {
		return m.SeasonId
	}
	return 0
}

type TeamRequest struct {
	TeamId               uint64   `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamRequest) Reset()         { *m = TeamRequest{} }
func (m *TeamRequest) String() string { return proto.CompactTextString(m) }
func (*TeamRequest) ProtoMessage()    {}
func (*TeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{8}
}

func (m *TeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamRequest.Unmarshal(m, b)
}
func (m *TeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamRequest.Marshal(b, m, deterministic)
}
func (m *TeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamRequest.Merge(m, src)
}
func (m *TeamRequest) XXX_Size() int {
	return xxx_messageInfo_TeamRequest.Size(m)
}
func (m *TeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamRequest proto.InternalMessageInfo

func (m *TeamRequest) GetTeamId() uint64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

type TeamResultRequest struct {
	// The Team ID that the Result set relates to
	TeamId uint64 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The number of results to return. If limit is not set the whole Result set for the Team
	// will be returned
	Limit *wrappers.UInt64Value `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// A filter to return Results before a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateBefore *wrappers.StringValue `protobuf:"bytes,3,opt,name=date_before,json=dateBefore,proto3" json:"date_before,omitempty"`
	// A filter to return Results after a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateAfter *wrappers.StringValue `protobuf:"bytes,4,opt,name=date_after,json=dateAfter,proto3" json:"date_after,omitempty"`
	// A filter to return based limited to either home or away results
	Venue *wrappers.StringValue `protobuf:"bytes,5,opt,name=venue,proto3" json:"venue,omitempty"`
	// A filter to limit the results returned associated to a specific season
	SeasonIds []uint64 `protobuf:"varint,6,rep,packed,name=season_ids,json=seasonIds,proto3" json:"season_ids,omitempty"`
	// Order the date column to return results in specific order
	Sort                 *wrappers.StringValue `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TeamResultRequest) Reset()         { *m = TeamResultRequest{} }
func (m *TeamResultRequest) String() string { return proto.CompactTextString(m) }
func (*TeamResultRequest) ProtoMessage()    {}
func (*TeamResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{9}
}

func (m *TeamResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamResultRequest.Unmarshal(m, b)
}
func (m *TeamResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamResultRequest.Marshal(b, m, deterministic)
}
func (m *TeamResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamResultRequest.Merge(m, src)
}
func (m *TeamResultRequest) XXX_Size() int {
	return xxx_messageInfo_TeamResultRequest.Size(m)
}
func (m *TeamResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamResultRequest proto.InternalMessageInfo

func (m *TeamResultRequest) GetTeamId() uint64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *TeamResultRequest) GetLimit() *wrappers.UInt64Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *TeamResultRequest) GetDateBefore() *wrappers.StringValue {
	if m != nil {
		return m.DateBefore
	}
	return nil
}

func (m *TeamResultRequest) GetDateAfter() *wrappers.StringValue {
	if m != nil {
		return m.DateAfter
	}
	return nil
}

func (m *TeamResultRequest) GetVenue() *wrappers.StringValue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *TeamResultRequest) GetSeasonIds() []uint64 {
	if m != nil {
		return m.SeasonIds
	}
	return nil
}

func (m *TeamResultRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

type TeamSeasonsRequest struct {
	TeamId uint64 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Order the name column to return seasons in specific order
	Sort                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TeamSeasonsRequest) Reset()         { *m = TeamSeasonsRequest{} }
func (m *TeamSeasonsRequest) String() string { return proto.CompactTextString(m) }
func (*TeamSeasonsRequest) ProtoMessage()    {}
func (*TeamSeasonsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{10}
}

func (m *TeamSeasonsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamSeasonsRequest.Unmarshal(m, b)
}
func (m *TeamSeasonsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamSeasonsRequest.Marshal(b, m, deterministic)
}
func (m *TeamSeasonsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamSeasonsRequest.Merge(m, src)
}
func (m *TeamSeasonsRequest) XXX_Size() int {
	return xxx_messageInfo_TeamSeasonsRequest.Size(m)
}
func (m *TeamSeasonsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamSeasonsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamSeasonsRequest proto.InternalMessageInfo

func (m *TeamSeasonsRequest) GetTeamId() uint64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *TeamSeasonsRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

type TeamStatRequest struct {
	Stat string `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	// The Team ID that the Result set relates to
	TeamId uint64 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The number of results to return. If limit is not set the whole Result set for the Team
	// will be returned
	Limit *wrappers.UInt64Value `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// A filter to return stats before a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateBefore *wrappers.StringValue `protobuf:"bytes,4,opt,name=date_before,json=dateBefore,proto3" json:"date_before,omitempty"`
	// A filter to return stats after a specific date
	// RFC3339 formatted string i.e "2006-01-02T15:04:05Z07:00"
	DateAfter *wrappers.StringValue `protobuf:"bytes,5,opt,name=date_after,json=dateAfter,proto3" json:"date_after,omitempty"`
	// A filter to return based stats limited to match being played either home or away
	Venue *wrappers.StringValue `protobuf:"bytes,6,opt,name=venue,proto3" json:"venue,omitempty"`
	// A filter to limit the results returned associated to a specific season
	SeasonIds []uint64 `protobuf:"varint,7,rep,packed,name=season_ids,json=seasonIds,proto3" json:"season_ids,omitempty"`
	// Order the date column to return stats in specific order
	Sort *wrappers.StringValue `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	// Return stats for opposing team
	Opponent             *wrappers.BoolValue `protobuf:"bytes,9,opt,name=opponent,proto3" json:"opponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TeamStatRequest) Reset()         { *m = TeamStatRequest{} }
func (m *TeamStatRequest) String() string { return proto.CompactTextString(m) }
func (*TeamStatRequest) ProtoMessage()    {}
func (*TeamStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{11}
}

func (m *TeamStatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStatRequest.Unmarshal(m, b)
}
func (m *TeamStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStatRequest.Marshal(b, m, deterministic)
}
func (m *TeamStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStatRequest.Merge(m, src)
}
func (m *TeamStatRequest) XXX_Size() int {
	return xxx_messageInfo_TeamStatRequest.Size(m)
}
func (m *TeamStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStatRequest proto.InternalMessageInfo

func (m *TeamStatRequest) GetStat() string {
	if m != nil {
		return m.Stat
	}
	return ""
}

func (m *TeamStatRequest) GetTeamId() uint64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *TeamStatRequest) GetLimit() *wrappers.UInt64Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *TeamStatRequest) GetDateBefore() *wrappers.StringValue {
	if m != nil {
		return m.DateBefore
	}
	return nil
}

func (m *TeamStatRequest) GetDateAfter() *wrappers.StringValue {
	if m != nil {
		return m.DateAfter
	}
	return nil
}

func (m *TeamStatRequest) GetVenue() *wrappers.StringValue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *TeamStatRequest) GetSeasonIds() []uint64 {
	if m != nil {
		return m.SeasonIds
	}
	return nil
}

func (m *TeamStatRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *TeamStatRequest) GetOpponent() *wrappers.BoolValue {
	if m != nil {
		return m.Opponent
	}
	return nil
}

func init() {
	proto.RegisterType((*CompetitionRequest)(nil), "statisticodata.CompetitionRequest")
	proto.RegisterType((*FixtureRequest)(nil), "statisticodata.FixtureRequest")
	proto.RegisterType((*FixtureSearchRequest)(nil), "statisticodata.FixtureSearchRequest")
	proto.RegisterType((*HistoricalResultRequest)(nil), "statisticodata.HistoricalResultRequest")
	proto.RegisterType((*ResultRequest)(nil), "statisticodata.ResultRequest")
	proto.RegisterType((*SeasonCompetitionRequest)(nil), "statisticodata.SeasonCompetitionRequest")
	proto.RegisterType((*SeasonRequest)(nil), "statisticodata.SeasonRequest")
	proto.RegisterType((*SeasonTeamsRequest)(nil), "statisticodata.SeasonTeamsRequest")
	proto.RegisterType((*TeamRequest)(nil), "statisticodata.TeamRequest")
	proto.RegisterType((*TeamResultRequest)(nil), "statisticodata.TeamResultRequest")
	proto.RegisterType((*TeamSeasonsRequest)(nil), "statisticodata.TeamSeasonsRequest")
	proto.RegisterType((*TeamStatRequest)(nil), "statisticodata.TeamStatRequest")
}

func init() {
	proto.RegisterFile("requests.proto", fileDescriptor_9c9ccec99da7c9b4)
}

var fileDescriptor_9c9ccec99da7c9b4 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x1d, 0xe7, 0xc7, 0x37, 0x5f, 0xf2, 0x09, 0xab, 0x52, 0xad, 0xf2, 0xd3, 0xc8, 0x12,
	0x28, 0xab, 0x84, 0x06, 0xd4, 0x0d, 0x62, 0x41, 0x2b, 0x21, 0xb2, 0x60, 0xe3, 0x00, 0x5b, 0x6b,
	0x62, 0x4f, 0xd2, 0x91, 0x1c, 0x8f, 0x99, 0xb9, 0xa6, 0xf4, 0x3d, 0x90, 0x90, 0x78, 0x05, 0x9e,
	0x8a, 0x37, 0x41, 0x33, 0xb6, 0x13, 0x27, 0x6d, 0x48, 0x1a, 0x56, 0xec, 0x92, 0xeb, 0x73, 0xee,
	0x9d, 0x7b, 0xce, 0xb1, 0x07, 0xba, 0x82, 0x7e, 0xce, 0xa8, 0x44, 0x39, 0x48, 0x05, 0x47, 0xee,
	0x74, 0x25, 0x12, 0x64, 0x12, 0x59, 0xc8, 0x23, 0x82, 0xe4, 0xe4, 0xc9, 0x9c, 0xf3, 0x79, 0x4c,
	0x87, 0xfa, 0xe9, 0x34, 0x9b, 0x0d, 0xaf, 0x05, 0x49, 0x53, 0x2a, 0x0a, 0xbc, 0xf7, 0xc3, 0x00,
	0xe7, 0x92, 0x2f, 0x52, 0x8a, 0x0c, 0x19, 0x4f, 0xfc, 0xbc, 0x9b, 0x73, 0x0a, 0xed, 0x90, 0x67,
	0x09, 0x8a, 0x9b, 0x80, 0x45, 0xd2, 0x35, 0x7a, 0xb5, 0xbe, 0xe5, 0x43, 0x51, 0x1a, 0x47, 0xd2,
	0x79, 0x0e, 0x96, 0xe4, 0x02, 0x5d, 0xb3, 0x67, 0xf4, 0xdb, 0xa3, 0x47, 0x83, 0x7c, 0xcc, 0xa0,
	0x1c, 0x33, 0x98, 0xa0, 0x60, 0xc9, 0xfc, 0x13, 0x89, 0x33, 0xea, 0x6b, 0xa4, 0x73, 0x06, 0x0d,
	0x26, 0x83, 0x30, 0x4b, 0xdd, 0x9a, 0xe6, 0x9c, 0xdc, 0xe2, 0x5c, 0x70, 0x1e, 0xe7, 0x8c, 0x3a,
	0x93, 0x97, 0x59, 0xea, 0x0d, 0xa1, 0xfb, 0x96, 0x7d, 0xc5, 0x4c, 0xd0, 0xf2, 0x5c, 0x8f, 0x01,
	0x66, 0x79, 0x25, 0x60, 0x91, 0x6b, 0xf4, 0x8c, 0xbe, 0xe5, 0xdb, 0x45, 0x65, 0x1c, 0x79, 0xdf,
	0x4d, 0x38, 0x2a, 0x18, 0x13, 0x4a, 0x44, 0x78, 0x55, 0xe1, 0x49, 0x4a, 0x24, 0x4f, 0x2a, 0xeb,
	0xd8, 0x79, 0x45, 0x6d, 0x33, 0x82, 0x7a, 0xcc, 0x16, 0x6c, 0xfb, 0x3a, 0x1f, 0xc7, 0x09, 0x9e,
	0xbf, 0x2c, 0x0e, 0xa7, 0xa1, 0xce, 0x6b, 0x68, 0x47, 0x04, 0x69, 0x30, 0xa5, 0x33, 0x2e, 0x68,
	0xb1, 0xd4, 0x9f, 0x85, 0x00, 0x45, 0xb8, 0xd0, 0x78, 0xe7, 0x15, 0xe8, 0x7f, 0x01, 0x99, 0x21,
	0x15, 0xae, 0xb5, 0x07, 0xdb, 0x56, 0xf8, 0x37, 0x0a, 0xbe, 0x54, 0xbf, 0xbe, 0xaf, 0xfa, 0xde,
	0x37, 0x03, 0x8e, 0xdf, 0x31, 0x89, 0x5c, 0xb0, 0x90, 0xc4, 0x3e, 0x95, 0x59, 0x8c, 0xa5, 0x38,
	0x3d, 0xf8, 0xef, 0x8a, 0x2f, 0x68, 0x80, 0x94, 0x2c, 0x56, 0xb2, 0x82, 0xaa, 0x7d, 0xa0, 0x64,
	0x31, 0x8e, 0x14, 0x82, 0x5c, 0x93, 0x9b, 0x25, 0xc2, 0xcc, 0x11, 0xaa, 0x56, 0x20, 0x8e, 0x4a,
	0x05, 0x95, 0x0e, 0x9d, 0x52, 0xa3, 0xd3, 0x75, 0x8d, 0xd4, 0x96, 0x76, 0x55, 0x05, 0x6f, 0x00,
	0x9d, 0xf5, 0xb3, 0xec, 0x30, 0x58, 0x82, 0x3b, 0xd1, 0xae, 0xdd, 0x91, 0xd9, 0xa7, 0xd0, 0x0d,
	0x57, 0xd5, 0x15, 0xbd, 0x53, 0xa9, 0x8e, 0xa3, 0xfb, 0x27, 0xd7, 0x7b, 0x0f, 0x9d, 0x7c, 0x68,
	0x39, 0xe9, 0x21, 0xd8, 0xcb, 0x34, 0xe9, 0x21, 0x35, 0xbf, 0x55, 0x86, 0x69, 0x73, 0x67, 0xf3,
	0xd6, 0xce, 0x67, 0xe0, 0xe4, 0xed, 0x94, 0x74, 0x72, 0x6b, 0x4f, 0x6b, 0xd5, 0xd3, 0x7b, 0x06,
	0x6d, 0x05, 0x2e, 0xb1, 0xc7, 0xd0, 0x5c, 0xf7, 0xaa, 0x81, 0xda, 0x05, 0xef, 0x97, 0x09, 0x0f,
	0x72, 0x60, 0x55, 0xd3, 0x6d, 0xf0, 0x7f, 0x2e, 0xf6, 0x23, 0xa8, 0x7f, 0xa1, 0x49, 0x46, 0xf7,
	0xca, 0x7d, 0x0e, 0xdd, 0x78, 0xf3, 0x1b, 0x9b, 0x6f, 0x7e, 0x99, 0x86, 0xe6, 0xde, 0x69, 0x08,
	0xc0, 0x51, 0x12, 0xe7, 0x16, 0xca, 0x9d, 0x1a, 0xdf, 0x3f, 0x6e, 0x3f, 0x6b, 0xf0, 0xbf, 0x9e,
	0x80, 0x64, 0x69, 0xa1, 0x03, 0x96, 0xfa, 0xb0, 0xeb, 0xde, 0xb6, 0xaf, 0x7f, 0x57, 0x47, 0x9a,
	0x77, 0xdb, 0x5a, 0x3b, 0xd8, 0x56, 0xeb, 0xaf, 0x6c, 0xad, 0x1f, 0x68, 0x6b, 0xe3, 0x50, 0x5b,
	0x9b, 0xdb, 0x6c, 0x6d, 0xed, 0x7d, 0x3d, 0x9d, 0x43, 0x8b, 0xa7, 0x29, 0x4f, 0x68, 0x82, 0xae,
	0xbd, 0xf3, 0x82, 0x5a, 0x62, 0xa7, 0x0d, 0xfd, 0xf4, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0xf3, 0x54, 0x34, 0x89, 0x07, 0x00, 0x00,
}
